baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Isaac Blog'
theme = "nightfall"


[menu]
  [[menu.header]]
    name = "Blog"
    weight = 0
    url = "blog"
  [[menu.header]]
    name = "About"
    weight = 1
    url = "about"
  [[menu.header]]
    name = "Docs/Examples"
    weight = 1
    url = "docs"

[params]
  [params.author]
    name = "Isaac Blog"  # Website and RSS feed author

published = false  # Show published data on post page

[[params.social]]
key = 0
name = "Github"
url = "https://github.com/Ismartba/"

[[params.social]]
key = 1
name = "LinkedIn"
url = "https://www.linkedin.com/in/isaacmartinezbarcia/"

[module]
[[module.imports]]
    path = 'github.com/hugomods/images'